#!/usr/bin/env python3
"""
Sample hardware install-guide / manual generator -- demonstrates that the same
branded engine + vector diagrams can produce manuals, not just validation
reports (rack mounting, rail-kit steps, mainboard service).

    python make_manual.py [out.pdf]      (default: manual_demo.pdf)

Reuses the Netweb/Tyrone branded header/footer from generate_report and the
vector diagrams from engine/diagrams.py.
"""

import datetime
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "engine"))

import diagrams as D            # noqa: E402
import generate_report as R     # noqa: E402
from reportlab.lib.units import mm  # noqa: E402
from reportlab.platypus import (   # noqa: E402
    BaseDocTemplate, Frame, PageBreak, PageTemplate, Paragraph, Spacer,
)

META = {
    "company": "Netweb Technologies India Limited",
    "report_title": "Installation Guide",
    "tier": "", "hostname": "Tyrone Camarero AI",
    "date": datetime.date.today().isoformat(),
}


def build(out_path: str) -> str:
    frame = Frame(R.MARGIN, 16 * mm, R.CONTENT_W, R.PAGE_H - R.TOP_BAR - 22 * mm, id="body")
    doc = BaseDocTemplate(out_path, pagesize=(R.PAGE_W, R.PAGE_H),
                          leftMargin=R.MARGIN, rightMargin=R.MARGIN,
                          topMargin=R.TOP_BAR + 6 * mm, bottomMargin=16 * mm,
                          title="Tyrone Camarero AI -- Installation Guide")
    doc.addPageTemplates([PageTemplate(id="body", frames=[frame],
                                       onPage=lambda c, d: R._draw_body(c, d, META))])

    story = [
        Paragraph("Tyrone Camarero AI — Installation Guide", R.S["h1"]),
        Paragraph("8U HGX-B200 AI server — rack mounting, rail-kit installation and mainboard "
                  "service. Generated by the CoreBench branded engine to show that the same "
                  "pipeline produces manuals, not only validation reports.", R.S["body"]),
        Spacer(1, 6),
        Paragraph("1. Rack Mounting", R.S["h2"]),
        Paragraph("The chassis occupies 8U. Install it in the lower third of the rack to keep the "
                  "centre of gravity low; a two-person lift is required.", R.S["body"]),
        Spacer(1, 4),
    ]
    rack = D.rack_elevation(total_u=42, occupants=[(20, 8, "Tyrone Camarero AI (8U)")],
                            width=70 * mm, u_h=2.7 * mm, title="Target U-position")
    rack.hAlign = "CENTER"
    story.append(rack)
    story.append(Spacer(1, 8))
    story.append(Paragraph("1.1 Rail-kit installation", R.S["h3"]))
    rails = D.railkit_steps(width=R.CONTENT_W)
    story.append(rails)

    story.append(PageBreak())
    story.append(Paragraph("2. Mainboard Layout &amp; Service", R.S["h2"]))
    story.append(Paragraph("CPU sockets, DIMM banks, PCIe/OCP slots and rear I/O. Populate DIMM "
                           "banks symmetrically per socket for full memory bandwidth.", R.S["body"]))
    story.append(Spacer(1, 4))
    # board name is auto-detected on real servers; the demo reads it from the fixture
    board = "auto-detected at run time (dmidecode)"
    try:
        import json
        fx = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                         "tests", "fixtures", "sample_results.json"), encoding="utf-8"))
        board = (fx.get("hardware", {}).get("system", {}) or {}).get("board") or board
    except Exception:
        pass
    mb = D.motherboard_map(width=R.CONTENT_W, spec=dict(D.DEFAULT_MB, name=board))
    story.append(mb)
    story.append(Spacer(1, 8))
    story.append(Paragraph("3. Safety", R.S["h2"]))
    story.append(R._bullets([
        "Always wear an ESD wrist strap when handling the mainboard or GPU trays.",
        "Disconnect all PSU inputs before service; the 8U shelf may draw >12 kW under load.",
        "Use a mechanical lift or two-person team for the 8U chassis.",
    ]))
    doc.build(story)
    return out_path


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "manual_demo.pdf")
    build(out)
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
